added evaluation workflow documents, updated readme
Open-Systems-Pharmacology/Montelukast-Model pull request #4
Opened 2020-07-15 10:42 UTC by Incei

2020-07-27 09:12 UTC, Yuri05 commented on evaluation/Input/Evaluation_plan.json
> +            "Path": "https://github.com/Open-Systems-Pharmacology/Montelukast-Model/releases/download/v1.1/Montelukast.json",
It's better to refer to the model snapshot by "Path": "../../Montelukast.json"

2020-11-28 18:11 UTC, Yuri05 commented on evaluation/Input/Evaluation_plan.json
> +            "Path": "https://github.com/Open-Systems-Pharmacology/Montelukast-Model/releases/download/v1.1/Montelukast.json",
@Incei Please fix the path, then we can merge this PR

2021-01-07 10:09 UTC, Yuri05 commented on evaluation/Input/Evaluation_plan.json
> +            "Path": "https://github.com/Open-Systems-Pharmacology/Montelukast-Model/releases/download/v1.1/Montelukast.json",
@Incei ping

2021-04-29 19:10 UTC, Yuri05 commented
@Incei ping

2021-06-30 17:08 UTC, Yuri05 commented on evaluation/Input/Content/titlepage.md
> +
same here
Compare e.g. https://github.com/Open-Systems-Pharmacology/Erythromycin-Model/blob/master/Evaluation/Input/Content/titlepage.md

2021-06-30 17:08 UTC, Yuri05 requested changes
s. last comment

2021-07-01 13:43 UTC, Yuri05 commented on evaluation/Input/Content/titlepage.md
> +
very close now
![grafik](https://user-images.githubusercontent.com/25061876/124134364-0e466f00-da83-11eb-9ed2-bc6730c53fb9.png)

2021-07-01 13:58 UTC, merged

2021-07-01 13:58 UTC, Yuri05 commented
A year of waiting was fully worth it 🤣

2021-07-01 14:16 UTC, Incei commented
> A year of waiting was fully worth it 🤣

After 100 corrections, totally!! 👯 🤣